### ISSUE TITLE
No valid constructor

### ISSUE THREAD

**Issue by DandyDev** [lloydmeta/enumeratum#140]
First of all: thanks for this awesome library! I hope it finds its way into core Scala proper :)

I'm having some issues with enums that override `entryName` when I use them together with Spark. I think the problem is in deserializing enums. This is the relevant enum code:

```scala
sealed abstract class PhBoardingStatus(override val entryName: String) extends EnumEntry
object PhBoardingStatus extends Enum[PhBoardingStatus] {

  val values: IndexedSeq[PhBoardingStatus] = findValues

  case object All           extends PhBoardingStatus("ALL")
  case object Closed        extends PhBoardingStatus("BC")
  case object Ignored       extends PhBoardingStatus("BI")
  case object NotOpen       extends PhBoardingStatus("BN")
  case object Open          extends PhBoardingStatus("BO")
  case object Suspended     extends PhBoardingStatus("BS")
}
```

When using this enum in Spark code, this stacktrace gets thrown:

```
2017-05-16 09:22:37 WARN  org.apache.spark.scheduler.TaskSetManager:66 - Lost task 0.0 in stage 17.0 (TID 33, kl1393d4.is.klmcorp.net): java.io.InvalidClassException: com.klm.flight720.dataSources.ph.PhBoardingStatus$Closed$; no valid constructor
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:150)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:790)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1775)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.DeserializationStream.readValue(Serializer.scala:159)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:189)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:186)
        ...
```

I assume this is because our abstract class only has a cosntructor with 1 argument, and no no-args constructor. Any idea how I can solve this?

**Comment by lloydmeta** [comment]
I think `case object`s already extend `Serializable` by default, so the problem might be as you said; the lack of a no-args constructor on the parent.

Perhaps something like this could work?

```scala
sealed trait PhBoardingStatus extends EnumEntry

object PhBoardingStatus extends Enum[PhBoardingStatus] {

  val values = findValues

  case object All       extends PhBoardingStatus { override val entryName = "ALL"}
  case object Closed    extends PhBoardingStatus { override val entryName = "BC" }
  case object Ignored   extends PhBoardingStatus { override val entryName = "BI" }
  case object NotOpen   extends PhBoardingStatus { override val entryName = "BN" }
  case object Open      extends PhBoardingStatus { override val entryName = "BO" }
  case object Suspended extends PhBoardingStatus { override val entryName = "BS" }
}
```

**Comment by DandyDev** [comment]
I'm gonna try this and will let you know if it works. Thanks for the tip!

**Comment by antonkulaga** [comment]
I also had such problem. I think it must be fixed because it mays API very verbose

**Comment by kantlove** [comment]
@lloydmeta your solution works but it leave the code more verbose unnecessarily. Is there a better fix for this situation?

**Comment by tsabran** [comment]
I've added this in the sealed abstract class instead, which I find less verbose and seems to work fine too:
```scala
    def this() = this("")
```

Yet I'm not familiar enough with this to understand why we need this no-param constructor and if it could be fixed directly in the EnumEntry...

**Comment by lloydmeta** [comment]
The problem is the lack of a no-arg constructor, which is required for Java Serialisation to work. 

If you don't need to customise the `entryName`, then a simple argument-free `abstract class` extending `EnumEntry` might work too.

@kantlove @antonkulaga if you have other ideas, send PRs.

**Comment by achelimed** [comment]
Hi,
I had the same problem but with my enum extending `enumeratum.EnumEntry.Lowercase` trait. I think that the problem is the same because `Lowercase` trait overrides the `entryName` too.
I have chosen the `def this() = this("")` option to resolve the problem because it is less verbose.
