### ISSUE TITLE
Unhelpful NSEE from namesToValuesMap

### ISSUE THREAD

**Issue by halfninja** [lloydmeta/enumeratum#254]
Passing an invalid name to `namesToValuesMap` returns an unhelpful NoSuchElementException with no message to indicate what the invalid value was
```
> domain.DocType.namesToValuesMap("Greg")
java.util.NoSuchElementException
  at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:569)
  at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
  ... 36 elided
```
Compare to `withName` which gives a much nicer message, but this doesn't help as `enumeratum-slick` uses `namesToValuesMap`, so you could optionally consider this as a bug in `SlickEnumColumnSupport`.

**Comment by lloydmeta** [comment]
Yeah, the `SlickEnumColumnSupport` can def be improved. Please feel free to send a PR.
